%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Funtion to numerically compute the mass matrix and contact jacobian of  %
% the bipedal robot RAMone                                                % 
%                                                                         %
%   C. David Remy cdremy@umich.edu                                        %
%   Matlab R2012b                                                         %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [M, J] = RAMoneMassMatrixJacobian(q, m1, m2, m3, j1, j2, j3, s1, s2, s3, l2, l3, rFoot)
%% extract states:
phi    = q(3);
alphaL = q(4);
betaL  = q(5);
alphaR = q(6);
betaR  = q(7);

%CONTACTJACOBIANL
%    JL = CONTACTJACOBIANL(X,Y,PHI,ALPHAL,BETAL,ALPHAR,BETAR,G,M1,M2,M3,LL1,LL2,LH,L2,L3,RFOOT,J1,J2,J3)
%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    19-Nov-2015 16:08:42
t2 = alphaL+phi;
t3 = cos(t2);
t4 = l2.*t3;
t5 = alphaL+betaL+phi;
t6 = cos(t5);
t7 = l3.*t6;
t8 = sin(t2);
t9 = l2.*t8;
t10 = sin(t5);
t11 = l3.*t10;
JL = reshape([1.0,0.0,0.0,1.0,rFoot+t4+t7+s1.*cos(phi),t9+t11+s1.*sin(phi),rFoot+t4+t7,t9+t11,rFoot+t7,t11,0.0,0.0,0.0,0.0],[2, 7]);

%CONTACTJACOBIANR
%    JR = CONTACTJACOBIANR(X,Y,PHI,ALPHAL,BETAL,ALPHAR,BETAR,G,M1,M2,M3,LL1,LL2,LH,L2,L3,RFOOT,J1,J2,J3)
%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    19-Nov-2015 16:08:41
t2 = alphaR+phi;
t3 = cos(t2);
t4 = l2.*t3;
t5 = alphaR+betaR+phi;
t6 = cos(t5);
t7 = l3.*t6;
t8 = sin(t2);
t9 = l2.*t8;
t10 = sin(t5);
t11 = l3.*t10;
JR = reshape([1.0,0.0,0.0,1.0,rFoot+t4+t7+s1.*cos(phi),t9+t11+s1.*sin(phi),0.0,0.0,0.0,0.0,rFoot+t4+t7,t9+t11,rFoot+t7,t11],[2, 7]);
J = [JL; JR];

%MASSMATRIX
%    M = MASSMATRIX(X,Y,PHI,ALPHAL,BETAL,ALPHAR,BETAR,G,M1,M2,M3,LL1,LL2,LH,L2,L3,RFOOT,J1,J2,J3)
%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    08-May-2015 21:30:54
t2 = cos(phi);
t3 = alphaL+betaL+phi;
t4 = cos(t3);
t5 = alphaR+betaR+phi;
t6 = cos(t5);
t7 = alphaL+phi;
t8 = cos(t7);
t9 = alphaR+phi;
t10 = cos(t9);
t11 = l3.*m3.*t4;
t12 = s2.*m2.*t8;
t13 = l2.*m3.*t8;
t14 = l3.*m3.*t6;
t15 = s2.*m2.*t10;
t16 = l2.*m3.*t10;
t17 = s3-l3;
t18 = m2.*2.0;
t19 = m3.*2.0;
t20 = m1+t18+t19;
t21 = sin(phi);
t22 = sin(t3);
t23 = sin(t5);
t24 = sin(t7);
t25 = sin(t9);
t26 = l3.*m3.*t22;
t27 = s2.*m2.*t24;
t28 = l2.*m3.*t24;
t29 = l3.*m3.*t23;
t30 = s2.*m2.*t25;
t31 = l2.*m3.*t25;
t32 = s1.*m2.*t2.*2.0;
t33 = s1.*m3.*t2.*2.0;
t59 = s3.*m3.*t4;
t69 = s3.*m3.*t6;
t34 = t11+t12+t13+t14+t15+t16+t32+t33-t59-t69;
t35 = s1.*m2.*t21.*2.0;
t36 = s1.*m3.*t21.*2.0;
t60 = s3.*m3.*t22;
t70 = s3.*m3.*t23;
t37 = t26+t27+t28+t29+t30+t31+t35+t36-t60-t70;
t38 = s1.^2;
t39 = alphaL+betaL;
t40 = cos(t39);
t41 = alphaR+betaR;
t42 = cos(t41);
t43 = cos(alphaL);
t44 = cos(alphaR);
t45 = cos(betaL);
t46 = cos(betaR);
t47 = s2.^2;
t48 = s3.^2;
t49 = l2.^2;
t50 = l3.^2;
t51 = l2.*l3.*m3.*t45.*2.0;
t52 = m3.*t48;
t53 = m3.*t50;
t54 = s1.*l3.*m3.*t40;
t55 = m2.*t47;
t56 = m3.*t49;
t57 = l2.*l3.*m3.*t46.*2.0;
t58 = s1.*l3.*m3.*t42;
t61 = s2.*s1.*m2.*t43;
t62 = s1.*l2.*m3.*t43;
t64 = s3.*l3.*m3.*2.0;
t65 = s3.*l2.*m3.*t45.*2.0;
t67 = s3.*s1.*m3.*t40;
t63 = j2+j3+t51+t52+t53+t54+t55+t56+t61+t62-t64-t65-t67;
t66 = l2.*l3.*m3.*t45;
t68 = j3+t52+t53-t64+t66-s3.*l2.*m3.*t45;
t71 = s2.*s1.*m2.*t44;
t72 = s1.*l2.*m3.*t44;
t73 = l2.*l3.*m3.*t46;
t74 = j3+t52+t53-t64+t73-s3.*l2.*m3.*t46;
t75 = j3+t52+t53-t64;
M = reshape([t20,0.0,t34,t11+t12+t13-t59,-m3.*t4.*t17,t14+t15+t16-t69,-m3.*t6.*t17,0.0,t20,t37,t26+t27+t28-t60,-m3.*t17.*t22,t29+t30+t31-t70,-m3.*t17.*t23,t34,t37,j1+j2.*2.0+j3.*2.0+t51+t57+m2.*t38.*2.0+m3.*t38.*2.0+m2.*t47.*2.0+m3.*t48.*2.0+m3.*t49.*2.0+m3.*t50.*2.0-s3.*l3.*m3.*4.0-s3.*s1.*m3.*t40.*2.0+s2.*s1.*m2.*t43.*2.0+s2.*s1.*m2.*t44.*2.0-s3.*s1.*m3.*t42.*2.0-s3.*l2.*m3.*t45.*2.0-s3.*l2.*m3.*t46.*2.0+s1.*l3.*m3.*t40.*2.0+s1.*l2.*m3.*t43.*2.0+s1.*l3.*m3.*t42.*2.0+s1.*l2.*m3.*t44.*2.0,t63,j3+t52+t53+t54-t64+t66-t67-s3.*l2.*m3.*t45,j2+j3+t52+t53+t55+t56+t57+t58-t64+t71+t72-s3.*s1.*m3.*t42-s3.*l2.*m3.*t46.*2.0,j3+t52+t53+t58-t64+t73-s3.*s1.*m3.*t42-s3.*l2.*m3.*t46,t11+t12+t13-s3.*m3.*t4,t26+t27+t28-s3.*m3.*t22,t63,j2+j3+t51+t52+t53+t55+t56-t64-t65,t68,0.0,0.0,-m3.*t4.*t17,-m3.*t17.*t22,j3+t52+t53+t54+t66-s3.*l3.*m3.*2.0-s3.*s1.*m3.*t40-s3.*l2.*m3.*t45,t68,t75,0.0,0.0,t14+t15+t16-s3.*m3.*t6,t29+t30+t31-s3.*m3.*t23,j2+j3+t52+t53+t55+t56+t57+t58+t71+t72-s3.*l3.*m3.*2.0-s3.*s1.*m3.*t42-s3.*l2.*m3.*t46.*2.0,0.0,0.0,j2+j3+t52+t53+t55+t56+t57-t64-s3.*l2.*m3.*t46.*2.0,t74,-m3.*t6.*t17,-m3.*t17.*t23,j3+t52+t53+t58+t73-s3.*l3.*m3.*2.0-s3.*s1.*m3.*t42-s3.*l2.*m3.*t46,0.0,0.0,t74,t75],[7, 7]);
end